workflows:
  build-android:
    name: Build Android APK
    working_directory: HNG
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
